Args = --no-fallback \
       --enable-url-protocols=http,https \
       --enable-all-security-services \
       --allow-incomplete-classpath \
       -H:+ReportExceptionStackTraces \
       -H:+AddAllCharsets \
       -H:IncludeResources=".*\.properties$" \
       -H:IncludeResources=".*\.g4$" \
       -H:+JNI
